{{- range $name, $obj := .Values.externalSecrets }}
{{- if not $obj.enabled }}{{- continue }}{{- end }}
---
apiVersion: {{ $obj.apiVersion | default "external-secrets.io/v1" }}
kind: ExternalSecret
metadata:
  name: {{ $name }}
  {{- with $obj.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $obj.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $spec := deepCopy $obj.spec }}
  {{- if $obj.templateFiles }}
    {{- $fdata := dict }}
    {{- range $key, $f := $obj.templateFiles }}
      {{- $content := $.Files.Get $f.path }}
      {{- if $f.tpl }}{{- $content = tpl $content $ | trim }}{{- end }}
      {{- if $f.appendMonitoringConfig }}{{- $content = printf "%s\n%s" $content (include "generic-app.monitoringConfig" $) }}{{- end }}
      {{- $_ := set $fdata $key $content }}
    {{- end }}
    {{- $spec = mergeOverwrite $spec (dict "target" (dict "template" (dict "data" $fdata))) }}
  {{- end }}
  {{- toYaml $spec | nindent 2 }}
{{- end }}
