{{- range $name, $obj := .Values.serviceAccounts }}
{{- if not $obj.enabled }}{{- continue }}{{- end }}
---
apiVersion: {{ $obj.apiVersion | default "v1" }}
kind: ServiceAccount
metadata:
  name: {{ $name }}
  {{- with $obj.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $obj.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
