{{- range $name, $obj := .Values.secretStores }}
{{- if not $obj.enabled }}{{- continue }}{{- end }}
---
apiVersion: {{ $obj.apiVersion | default "external-secrets.io/v1" }}
kind: SecretStore
metadata:
  name: {{ $name }}
  {{- with $obj.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $obj.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml $obj.spec | nindent 2 }}
{{- end }}
